theme = "semi-native"
icons = "awesome5"

[[block]]
block = "networkmanager"
on_click = "lxterminal -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
ap_format = "{strength}"
device_format = "{icon}{ap}"

[[block]]
driver = "pulseaudio"
block = "sound"
step_width = 5

[[block]]
block = "battery"
interval = 5
format = "{percentage}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%b/%Y %R"